### ISSUE TITLE
s init 提示 No available provider for fc-event-nodejs10

### ISSUE THREAD

**Issue by jjeejj** [Serverless-Devs/docs#3]
按照文档 s config add 添加阿里云的配置后，执行 s init fc-event-node10 提示错误
`Initialization failed: No available provider for fc-event-nodejs10`

**Comment by anycodes** [comment]
非常好的问题。感谢您对Serverless Devs的支持。

刚才我看了一下文档，文档写的是`s init fc-event-nodejs10`，我看了一下应用中心，貌似已经删掉了这个应用，所以我重新更新了一下文档，您可以`s init nodejs10`。

那么这里引出来一个新的问题：我们怎么知道init后面的的project名字呢？

其实我们可以通过两个途径：
1. `s search`，例如您熟悉python语言，那么您就可以`s search python`，你就可以看到结果：
```
Name           Provider & Type      Description

python3-http   Alibaba@Application  快速部署一个Python3的HTTP类型的Hello World函数到阿里云函数计算。
python27-http  Alibaba@Application  快速部署一个Python2.7的HTTP类型的Hello World函数到阿里云函数计算。
python27-http  Tencent@Application  快速部署一个Python2.7的Http类型的Hello World函数到腾讯云函数计算。
python36-http  Tencent@Application  快速部署一个Python3.6的Http类型的Hello World函数到腾讯云函数计算。
python3        Tencent@Application  快速部署一个Python3.6的Event类型的Hello World函数到腾讯云函数计算。
python2        Tencent@Application  快速部署一个Python2.7的Event类型的Hello World函数到腾讯云函数计算。
python3        Alibaba@Application  快速部署一个Python3的Event类型的Hello World函数到阿里云函数计算。
python27       Alibaba@Application  快速部署一个Python2.7的Event类型的Hello World函数到阿里云函数计算。
```

这个时候你就可以直接`s init ` + name，例如: `s init python3 -p alibaba`

2. 第二种方法就比较炫酷了，你可以直接通过`s gui`或者`s init --gui`，拉起GUI页面，进行搜索，创建，可以[GUI文档](https://github.com/Serverless-Devs/docs/blob/master/%E5%BA%94%E7%94%A8%E4%B8%AD%E5%BF%83/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.md)，也可以参考这个[案例](https://github.com/Serverless-Devs/docs/blob/master/%E5%BA%94%E7%94%A8%E4%B8%AD%E5%BF%83/%E5%85%A5%E9%97%A8%E6%A1%88%E4%BE%8B.md)
