### ISSUE TITLE
 Can deploy private?

### ISSUE THREAD

**Issue by fly3366** [Serverless-Devs/docs#4]
Or has any s-ci impl doc? like login, push etc.

**Comment by anycodes** [comment]
I could not understand 'deploy private'.

But I think if you use serverless devs you can deploy packages to  public cloud or private cloud.

Now there are some cloud providers which you can config directly，if there are not the cloud provider which you want to deploy to, or private cloud, you can provide component by yourself and use access.yaml. 

Step 1:
    Develop a component

Step 2:
    Config your access.yaml in your project directory

Step 3:
    Deploy


If you want to develop a component , you could reference [Development components](https://github.com/Serverless-Devs/docs/blob/master/Serverless-Devs/Package%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97.md)
If you want to know the access.yaml, you could reference [Through file configuration](https://github.com/Serverless-Devs/docs/blob/master/%E5%BC%80%E5%8F%91%E8%80%85%E5%B7%A5%E5%85%B7/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8/%E5%AF%86%E9%92%A5%E9%85%8D%E7%BD%AE.md#%E9%80%9A%E8%BF%87%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE)

About these docs, we will provide English Docs soon.
