### ISSUE TITLE
s gui  "Error"  no client

### ISSUE THREAD

**Issue by cjzy-1** [Serverless-Devs/docs#6]
s gui

Check that you don’t have a gui client, download it now, it will take you about 1 minute.
Current system : linux, current client version: 0.0.20 
⢫ Downloading ... Error: Response code 404 (Not Found)

**Comment by anycodes** [comment]
Is it convenient to tell you where you are? Is this the same error after you try again?

**Comment by hanxie-crypto** [comment]
I'm sorry that the Linux version of GUI was tested this week and is expected to open next week. I will inform you then

**Comment by cjzy-1** [comment]
> I'm sorry that the Linux version of GUI was tested this week and is expected to open next week. I will inform you then

好的，谢谢！

**Comment by cjzy-1** [comment]
> Is it convenient to tell you where you are? Is this the same error after you try again?

我在北京，在我的阿里云ecs（青岛节点，ubuntu 18.4）上运行s gui 时的提示，刚刚还是有同样的错误提示的。

**Comment by anycodes** [comment]
了解。
如果是linux操作系统，我们暂时还不支持GUI页面，但是也快了，预计下周，我们就会出Linux版本的GUI页面。
但是在没有可视化程序的操作系统中，可能是没办法使用的，例如某些ubuntu-server等

**Comment by cjzy-1** [comment]
> 了解。
> 如果是linux操作系统，我们暂时还不支持GUI页面，但是也快了，预计下周，我们就会出Linux版本的GUI页面。
> 但是在没有可视化程序的操作系统中，可能是没办法使用的，例如某些ubuntu-server等

也就是说Serverless-Devs我应该在我个人本地电脑上运行，而不是云服务器上，是吧

**Comment by anycodes** [comment]
不是的，Serverless-Devs分为两部分：
命令行工具（就是cli）：这一部分是在云服务器上面，本地上面都可以用的，他是一个无UI界面的，你通过`npm install -g @serverless-devs/s`安装完成之后，就已经有这个能力了；
应用中心（就是在cli中执行s gui）：这一部分是我们为了简化cli的使用方法，做的一个gui，前提是，您要有一个显示gui的能力。如果是Server的话，一般不能显示这些，例如你没办法在Ubuntu Serverless打开钉钉，就算你打开了，你也看不到具体的页面，一个道理。

命令行工具的样子是：
![image](https://user-images.githubusercontent.com/21079031/97825527-e1766800-1cf9-11eb-8604-b5019d1c38a5.png)
你可以搜索应用，创建应用，进行部署，查看日志......
![image](https://user-images.githubusercontent.com/21079031/97825569-05d24480-1cfa-11eb-92f0-deba171439c9.png)

可视化的GUI页面是：
![image](https://user-images.githubusercontent.com/21079031/97825588-12569d00-1cfa-11eb-8d7c-80c6e90862dc.png)
这一部分是需要图形化界面的。例如您在云服务器上，如果是windows的云服务器，有可视化界面的，那就可以用，如果您的云服务器是黑窗窗，没有可视化界面，这个页面是没办法显示出来的。


综上所述：Serverless-Devs是可以在本地电脑运行，也可以在云服务器上运行的。但是如果您的云服务器不具备可视化图形界面，则没办法通过GUI来使用Serverless-Devs，但是丝毫不影响Serverless-Devs的其他功能。

**Comment by cjzy-1** [comment]
好的，了解了。谢谢！
