### ISSUE TITLE
gui和App Store功能是被砍掉了吗

### ISSUE THREAD

**Issue by wlmvp** [Serverless-Devs/docs#8]

**Comment by anycodes** [comment]
感谢您对Serverless Devs的关注，我们的GUI和App Store没有被砍掉，我们正在进行升级，预计6月会发布全新的GUI和App Store。

- 全新的GUI是Serverless Desktop
- 全新的App Store是Serverless HUB

感谢您的关注和支持，继续期待吧，我们一起玩转Serverless

**Comment by wlmvp** [comment]
优秀 期待ing
